name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        env:
          MEILI_MASTER_KEY: "masterKey"
          MEILI_NO_ANALYTICS: "true"
        ports:
          - "7700:7700"

    name: Deno tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Check formatting
        run: deno task -r fmt

      - name: Run linter
        run: deno task -r lint

      - name: Run tests
        run: deno task -r test
